# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - sudo apt-get install -qq libgdal-dev libproj-dev
    # teamr R deps
  - sudo apt-get install -qq r-cran-rcpp r-cran-mgcv r-cran-foreach r-cran-sp r-cran-abind 
    # dependency R deps
  - sudo apt-get install -qq r-cran-gtools r-cran-rgl

install:
  - ./travis-tool.sh install_github azvoleff/spatial.tools
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_github hadley/devtools
  - ./travis-tool.sh install_github hadley/testthat

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change
